### PR TITLE
Replace `fasterq-dump` With `fastq-dump -Z` and Named Pipes

### PR DESCRIPTION
**Pull request by Miserlou**
## Purpose/Implementation Notes

Using `fasterq-dump` at scale causes disk thrashing that kills our overall throughput. We tried solving this using ramdisks so that `fasterq-dump` just uses RAM rather than disk, but Nomad isn't ready for that as ramdisks aren't supported in `0.8.0` and don't work properly in `0.9.0-beta3`.

This solution uses named pipes created with `mkfifo` to pass the output from `fastq-dump -Z` from the `stdout` directly into Salmon. This doesn't use any disk IO as long as there is enough RAM available so that no paging is necessary.

I think this is probably a short-term fix but I think it'll get the job done. 

## Methods
Because we don't have direct access to FASTQ files directly any more, we can't use `fastqc`, so that step gets skipped entirely. Similarly, we can't use our old technique for calculating the length of the transcriptome index to use, so we parse the output of `sra-stats --xml --statistics` using the `untangle`.

There is a difference between in single and paired end reads, so we use `tee` and `grep` to split the streams in place, thanks so a solution posted online by Graham LaRue from UC Merced.

Since I think this fix will be temporary, I left the previous functionality in place and just commented it out of the pipeline.

## Types of changes
- New feature (non-breaking change which adds functionality)

## Functional tests
Existing tests pass without modification, which is a good sign. May need one more test for assuring that both single and paired end reads work as expected (although they did in my manual testing).

### CODE REVIEW

**Comment by cgreene** [comment]
Would close #1000

**Comment by jaclyn-taroni** [comment]
☝️ Fixed that issue number, also closes #873

**Comment by Miserlou** [comment]
@arielsvn can you review this? I'd like to try it on staging

**Comment by luizirber** [comment]
Hi! I saw this PR and the previous discussion about SRA files, and I'm curious about a few things:

- Do you need the Named Pipes because salmon doesn't read files from stdin? I use the `fastq-dump -Z` output in [wort][0] to feed it into sourmash, but are there other benefits in making a named pipe (better buffering or more control?)
- I also saw [this post][1] from some time ago, do you have any other tricks to make downloading faster? =]

[0]: https://github.com/dib-lab/wort/blob/fbeeeb78a669dec8049e8d78bf8b6e2d7c38d488/wort/blueprints/compute/tasks.py#L41
[1]: https://www.ccdatalab.org/blog/a-desperate-plea-for-a-free-software-alternative-to-aspera

**Comment by Miserlou** [comment]
Yes, Salmon doesn't read directly from `stdin`, there is an open ticket somewhere around Salmon related to that. There the author suggests using `/dev/fd0` but here we use FIFOs for the same purpose. Particularly for paired end reads, Salmon expects inputs as two separate files and can't handle interleaved pairs.

Aspera sucks. I'm praying that QUIC+HTTP/3 will emerge victorious from the hell pit of IETF standardizations as a suitable alternative, everybody will make the switch quickly (that should be the easy part given the absurdly high cost of Aspera server licenses), and Aspera will be one of those bad memories of internet past, like Java Applets and Adobe Shockwave.

**Comment by Miserlou** [comment]
Seems to be working, `sra-stat` is occasionally quite slow but Salmon seems fast.

**Pull request merged**
