### PR TITLE
Add compendium-specific README

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
## Issue Number

#983 

## Purpose/Implementation Notes

We want to include a README that is specific to species compendia downloads. This PR covers the Markdown file that we would include. Backend changes to include this file, rather than `README_DATASET.md`, in a download are still needed.

I've tailored the **Contents** section to be more specific to compendia and I've also added a **Notes and observations** that points users to the analyses that support our processing choices and our series of exploratory data analyses.

## Functional tests

N/A

## Checklist

_Put an `x` in the boxes that apply._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
@cgreene can you take a look at the contents of the **Notes and observations** section and see if that's consistent with what we chatted about yesterday?

@dvenprasad we will need to work together on tweaking this to be consistent with whatever changes you're going to make to `README_DATASET.md`.

**Comment by cgreene** [comment]
Looks good to me - but it's not one sentence per line :)

**Comment by jaclyn-taroni** [comment]
I did that on purpose, but I have no idea what my rationale was! Will change.

**Comment by jaclyn-taroni** [comment]
@Miserlou will make the changes needed to package this as part of the compendium on this PR

**Pull request merged**
