### PR TITLE
Add Support for Non-BrainArray CELs, with Test

### PR DESCRIPTION
**Pull request by Miserlou**
## Issue Number
https://github.com/AlexsLemonade/refinebio/issues/64

## Purpose/Implementation Notes

Small change to avoid failure when there is no BA package. I think this works as intended.

## Types of changes

What types of changes does your code introduce?

- New feature (non-breaking change which adds functionality)

## Functional tests

New test for sample GSM45588.PCL added

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cgreene** [comment]
Mentioning #186 so that this PR gets cross-referenced there for help finding cases we may need to run gProfiler on later (re: convo w/ @jaclyn-taroni ).

**Comment by jaclyn-taroni** [comment]
This looks like it is doing what is desired and satisfies #64. Do you have `GSM45588.PCL` so we can take a look at it and see if it is as I expect? (Attaching it here is fine, even just posting the first 10 lines would be helpful.)

**Comment by Miserlou** [comment]
```
GSM45588.CEL
AFFX-Athal_GAPDH_at	-0.24092314
AFFX-Athal_actin_at	-0.04730129
AFFX-Athal_ubq_at	-0.00121378
AFFX-Bsubtilis_dapB_at	-0.14936704
AFFX-Bsubtilis_lys_at	-0.08952597
AFFX-Bsubtilis_pheB_at	-0.05835295
AFFX-Bsubtilis_thrC_at	-0.19631491
AFFX-Bsubtilis_trpD_at	-0.04115112
AFFX-YEL002C_WPB1_at	-0.00230101
AFFX-YEL018W_at	-0.16018818
AFFX-YEL024W_RIP1_at	-0.03301559
AFFX-YER022W_SRB4_at	-0.04529586
AFFX-YER148W_SPT15_at	-0.12017056
AFFX-YFL039C_ACT1_at	-0.00332506
PA0001_dnaA_at	0.11799504
PA0002_dnaN_at	0.66781084
PA0003_recF_at	-0.06941581
PA0004_gyrB_at	-0.02756669
PA0005_at	-0.10733761
PA0006_at	-0.02982982
PA0007_at	0.25386567

[ ... ]

ig_901046_901934_at	-0.06789654
ig_901934_901046_at	1.06417389
ig_991198_991830_at	0.00611707
ig_991830_991198_at	0.0036976
```
[GSM45588.PCL.zip](https://github.com/AlexsLemonade/refinebio/files/1988909/GSM45588.PCL.zip)

**Comment by jaclyn-taroni** [comment]
That PCL LGTM 👍 it has the number of rows I would expect based on [`GPL84`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL84), row names are probe ids, the single column contains expression values

**Pull request merged**
