### PR TITLE
Dualsmash Part 2: Transform and Smash

### PR DESCRIPTION
**Pull request by Miserlou**
## Issue Number

https://github.com/AlexsLemonade/refinebio/issues/330
Depends on: https://github.com/AlexsLemonade/refinebio/pull/355
Conflicts with: https://github.com/AlexsLemonade/refinebio/pull/307

## Purpose/Implementation Notes

Adds ability to smash RNASeq/Microarray data together. 

## Methods
Jackie recommended: 

```
aggregating by experiment -> return untransformed output from tximport
aggregating by species -> log2(x + 1) tximport output
```

For `SPECIES`, this is accomplished by: 

```
data = data + 1
data = np.log2(data)
```

I don't understand the inclusion of `aggregating by experiment`, since there are no experiments (as far as I am aware) which use both technologies at once. Still, if it does occur, the transformation above won't.

## Types of changes

What types of changes does your code introduce?
- New feature (non-breaking change which adds functionality)

## Functional tests

New tests and new test data is provided.

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
To clarify: If a user has selected both microarray and RNA-seq experiments but wants to aggregate by experiment (i.e., they are not actually combining technologies), then do not perform the transformation. It sounds like we're on the same page 👍

**Comment by Miserlou** [comment]
Yes. However, this conflicts with some behavior in #307: https://github.com/AlexsLemonade/refinebio/pull/307/files#diff-04738c4482565d676e6b7a40dc060df9R87

Does that check need to be a) made technology-aware or b) removed entirely?

**Comment by jaclyn-taroni** [comment]
> Does that check need to be a) made technology-aware

As in check only for microarray data? I like that idea.

**Comment by Miserlou** [comment]
Okay, I added that to the other PR.

**Pull request merged**
