### PR TITLE
Remove unused and broken _verify_result function from qn_reference.py

### PR DESCRIPTION
**Pull request by kurtwheeler**
## Issue Number

#1954 

## Purpose/Implementation Notes

While working on #1954 I cleaned up the qn_reference.py file, and noticed that there was an undefined variable name in `_verify_result`. Looking into it more, I realized there was no data object in that job that could be used as `smashed_frame`. This just looks super invalid. The comment it got that code from (https://github.com/AlexsLemonade/refinebio/issues/599#issuecomment-422132009), used a microarray zebrafish compendia as the input. I have no idea what this was supposed to be comparing against.

## Methods

@jaclyn-taroni this is a code cleanup PR, so it's not actually changing what we're doing. However, should we be doing any kind of verification of QN targets? @davidsmejia had the idea of comparing against the previous QN target that was generated for that organism, but it's not clear how stringent we should be or what to do in the case where the QN target is supposed to be changing a lot (like for example, going from ~9k genes to ~20k genes).

## Types of changes

- Cleanup

## Functional tests

This code isn't even called, unit tests should be sufficient.

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Oooo this is a good question. I would say that I would be surprised, at least for popular organisms, if the largest platform changed. However, if/when we update the Brainarray version, I expect that we might see a change in the _number of genes_ by a few percent which makes things challenging.

**Comment by jaclyn-taroni** [comment]
Can we create a ticket for the verification stuff? I don't think we'll arrive at a solution before the holiday and I don't want it to get lost.

**Comment by cgreene** [comment]
I updated merged (one line got commented in a block that had fixed indentation). Let's see if test pass now.

**Comment by cgreene** [comment]
Tests passed. I think this is good to go out :+1:

**Pull request merged**
