### PR TITLE
[Master] Various Changes, Including Migrations 

### PR DESCRIPTION
**Pull request by Miserlou**

### CODE REVIEW

**Comment by kurtwheeler** [comment]
Is this going to be deployed as a hotfix?

**Comment by Miserlou** [comment]
If avoidable no, if not yes.

**Comment by kurtwheeler** [comment]
Ok, if it is can you change the PR's title to include [HOTFIX]?

**Comment by Miserlou** [comment]
But this is to the master branch (2 approvals), normal hotfixes go off of dev (1 approval)

**Comment by kurtwheeler** [comment]
Oh yeah duh....

**Pull request merged**
