### PR TITLE
Remove `files` from the sample details serializer

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

#1071 

## Purpose/Implementation Notes

Remove `files` from the response of the API, on the detailed samples endpoint (`/samples`).

### CODE REVIEW

**Comment by Miserlou** [comment]
I think this should be done with a new serializer, there are cases where we'll want to see the files assoc'd with a result outside of sample context.

**Comment by arielsvn** [comment]
But if we add a new serializer, then the `ComputationalResultSerializer` won't be used anywhere else, since it was added specifically for the detailed samples endpoint. 

Do you think we should still keep it in case we need it in the future?

**Comment by Miserlou** [comment]
We should have a results endpoint

**Comment by arielsvn** [comment]
I see, I had missed that endpoint.

Added now a new serializer only with the fields we use in the frontend. Let me know what do you think @Miserlou

**Pull request merged**
