### PR TITLE
Remove unnecessary R packages from affymetrix docker image

### PR DESCRIPTION
**Pull request by dongbohu**
## Issue Number
#336 

## Purpose/Implementation Notes
Remove unnecessary packages from Affymetrix Docker image

## Functional tests
Tested on my local desktop.

### CODE REVIEW

**Comment by dongbohu** [comment]
@Miserlou: I checked with @jaclyn-taroni and those `pd.*` packages are required.

**Comment by jaclyn-taroni** [comment]
One thought that came up in my discussion with @dongbohu: make _organism-specific_ Affymetrix images. So all the platform design and Brainarray packages from one organism would live on the same image and the organism for an assay would dictate what Docker image is used for that processor. The rationale for having an organism-centric image rather than one for every single platform is because, as has been noted elsewhere, sometimes the CEL header does not match the platform listed in the data source but we can probably assume that the organism label is correct the majority of the time.

**Comment by dongbohu** [comment]
Hi @jaclyn-taroni: I was about to close this PR, then I noticed lines 19-22:
https://github.com/AlexsLemonade/refinebio/blob/dev/workers/affymetrix_dependencies.R#L19
Should we delete them too?

**Comment by jaclyn-taroni** [comment]
Sure. I have not evaluated whether or not every single package will be required. I just listed the ones that jumped out at me in #338.

**Pull request merged**
