### PR TITLE
Add `ProcessorJobError` to be used when processor jobs fail

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

N/A

## Purpose/Implementation Notes

Got this idea to refactor how we handle errors on the processor jobs, instead of using the `job_context['failure_reason']` this uses an exception that is handled in a single place.

What do you think @kurtwheeler?

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

None

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kurtwheeler** [comment]
I think I like this I just want to think on it a bit more!!

**Comment by kurtwheeler** [comment]
BTW I think you should pull `dev` into this branch.

**Comment by arielsvn** [comment]
Just merged `dev` I'm going to wait until the tests pass to close this.

Yeah, I think this will allow us to simplify the logic to handle errors in the processor jobs and raise exceptions instead of working with `job_context["success"]` and `job_context["failure_reason"]`

> I think we can even extend the exception class to include additional context to log in the error message!

How? This sounds like a good idea! We can do it in a different PR.

**Comment by kurtwheeler** [comment]
> How? This sounds like a good idea! We can do it in a different PR.

I agree and I made an issue for it: https://github.com/AlexsLemonade/refinebio/issues/1874

**Pull request merged**
