### PR TITLE
Decompose annotations in smasher's output TSV file

### PR DESCRIPTION
**Pull request by dongbohu**
## Issue Number

#515
#532 

## Purpose/Implementation Notes
- This PR extracts some important fields nested in sample annotations and save them as the new columns in smasher's output tsv files.
- Some annotation fields are ignored in TSV file.
- To make the testing easier, the code that writes tsv files are refactored into multiple functions.

## Types of changes

What types of changes does your code introduce?

- New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

Please attach any screenshots that illustrate these changes.

### CODE REVIEW

**Comment by dongbohu** [comment]
@jaclyn-taroni: Here is a tarball that includes all tsv files generated by the test cases.
[tsv_tests.tar.gz](https://github.com/AlexsLemonade/refinebio/files/2397447/tsv_tests.tar.gz)

The input metadata is here:
https://github.com/AlexsLemonade/refinebio/blob/b7384915366f2bb0869da6c9ea435a3ffa93ca91/workers/data_refinery_workers/processors/test_smasher.py#L947

The columns in tsv files are in this order:
(1) refinebio_title (same as original `sample_id`)
(2) other `refinebio` columns in alphabetic order
(3) annotation-related columns in alphabetic order

Please let me know if you have any questions.

**Comment by Miserlou** [comment]
Looking at these outputs, it seems like there are empty columns, even if all of the samples in a file don't have values. Is that desired behavior?

**Comment by dongbohu** [comment]
@Miserlou: Yes, the TSV files generated in the same dataset will have same columns (so that a user can compare them easily).

**Comment by jaclyn-taroni** [comment]
Output LGTM, @dongbohu thanks! 👍

**Pull request merged**
