### PR TITLE
Remove Affy Control Probes When Smashing 

### PR DESCRIPTION
**Pull request by Miserlou**
## Issue Number

#550

## Purpose/Implementation Notes

Trivial implementation

## Types of changes
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
This has implications for the QN target that has already been generated, correct?

**Comment by Miserlou** [comment]
Ooo, that's a good point. Should this happen after the QN step?

**Comment by jaclyn-taroni** [comment]
I would ideally remove these when we generate the QN target (other platforms don't have the same control probes or don't have probes at all) _and_ then we should take these out prior to QN when we smash.

**Comment by Miserlou** [comment]
Okay, cool. That will happen from this PR, but we will need to regenerate our QN targets on prod.

**Pull request merged**
