### PR TITLE
fix slack webhook on slackpost.sh script

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

N/A

## Purpose/Implementation Notes

We have a notification on slack when a deploy finishes successfully that it wasn't working since we updated the slack webhooks.

This fixes the url.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Functional tests

Tested script and saw notification on #robots

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cgreene** [comment]
> We recently discovered a publicly accessible incoming webhook associated with your Slack workspace, alexslemonade.slack.com. This can happen when a webhook URL is posted on a public site, such as a code-sharing forum. None of your data is at risk — webhooks can only send messages into Slack and cannot access any data.
> 
> Though your data is not at risk of being exposed through a webhook, we've invalidated the publicly exposed webhook URL and generated a new one on your behalf. We realize that this may cause some disruption for you or your team; however, protecting your team's security and privacy is important to us. Here is the webhook we found (with its previous URL):

**Comment by cgreene** [comment]
We should probably make these types of URLs and contact email addresses configurable. If someone deployed their own instance of refine.bio they probably would want the information to go to them and not us.

**Comment by arielsvn** [comment]
We moved the URL to an environment variable in circle ci.

**Comment by cgreene** [comment]
Is there documentation somewhere of what environment variables one needs to set on Circle CI to run the deploy process/etc? Just curious - not to make for this PR. If not, is this something we should have docs for? If so, that might be a good ticket.

**Comment by arielsvn** [comment]
We have some documentation on the circleci environment variables on https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/deploy_box_instance_data.sh. Updated them now :)

**Comment by arielsvn** [comment]
Good catch @kurtwheeler, added a check now

**Pull request merged**
