### PR TITLE
Test LGTM Plugin

### PR DESCRIPTION
**Pull request by cgreene**
## Issue Number

Somewhat related to #1686

## Purpose/Implementation Notes

Make a few small changes to clean up LGTM issues. Check how the plugin works on PRs.

## Methods

N/A

## Types of changes

What types of changes does your code introduce?

- Bugfix (non-breaking change which fixes an issue)

## Functional tests

N/A, but I did search the files to make sure these weren't used.

## Checklist

_Put an `x` in the boxes that apply._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

Please attach any screenshots that illustrate these changes.

### CODE REVIEW

**Comment by cgreene** [comment]
Feel free to close this once LGTM processes - looks like I botched the pull into master. I just had to make a new PR to see what it looked like 😁

**Comment by cgreene** [comment]
Ok - LGTM doesn't look too chatty on this - does anyone object to me leaving it enabled?

**Comment by arielsvn** [comment]
Will it make an additional comment after new commits? I think this happened in the FE project, and we decided to leave it enabled but disable the comment part.

**Comment by cgreene** [comment]
Since it made one above, it appears that the answer is yes. Do you remember how to disable that?

**Comment by arielsvn** [comment]
Yes, just disabled the comments!

**Pull request closed without merging**
