### PR TITLE
Update r_dependencies.R

### PR DESCRIPTION
**Pull request by dongbohu**
## Issue Number

#71

## Purpose/Implementation Notes

Add version numbers for all R packages installed by this R script.

## Types of changes

What types of changes does your code introduce?

- New feature (non-breaking change which adds functionality)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.
- Tested on a generic Ubuntu 16.04 docker image

## Checklist

_Put an `x` in the boxes that apply._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

Please attach any screenshots that illustrate these changes.

### CODE REVIEW

**Comment by dongbohu** [comment]
By the way, don't worry about the failed check by CircleCI. Rich has filed another PR to fix it. This PR is totally independent from the failed test.

**Comment by dongbohu** [comment]
@jaclyn-taroni I updated the line in `workers/data_refinery_workers/processors/array_express.py` and include it in this PR. Please take a look. If it is okay, I will close this PR and related issues.

**Comment by jaclyn-taroni** [comment]
@dongbohu where is the species information (e.g., if sample is _H. sapiens_, `hs` should be included in that string) now coming from?

**Comment by dongbohu** [comment]
@jaclyn-taroni I thought the species name would be included in `package_name_without_version` already. I am not familiar with this part of code. Need to dig deeper to find where the species name is.

**Comment by dongbohu** [comment]
@jaclyn-taroni If you have any idea where the species information is located, please feel free to let me know. Thanks.

**Comment by jaclyn-taroni** [comment]
Unfortunately, I think @kurtwheeler or possibly @Miserlou are more likely to be able to answer that question in a timely manner

**Comment by dongbohu** [comment]
@jaclyn-taroni Issue #85 is not as easy to fix as I thought. I have reverted the last commit and am going to close the current PR and open another one to address #85.

**Comment by jaclyn-taroni** [comment]
👌 sounds good

**Pull request merged**
