### PR TITLE
Upgrade package versions that github auto-opened PRs for.

### PR DESCRIPTION
**Pull request by kurtwheeler**
## Issue Number

#1904 
#1903 
#1902 
#1901 
#1900 
#1899 
#1898

## Purpose/Implementation Notes

Github opened 7 PRs to do this, and it doesn't do it right because it directly modifies requirements.txt instead of first adding the deps to requriements.in.

## Types of changes

- Security

### CODE REVIEW

**Comment by cgreene** [comment]
I closed the GitHub-generated ones to reduced clutter.

**Comment by kurtwheeler** [comment]
I was waiting until the tests for this to pass before doing so.

**Comment by arielsvn** [comment]
We could test this on staging before deploying

**Comment by kurtwheeler** [comment]
Good call @arielsvn

**Pull request merged**
