### PR TITLE
Send platform names on the platform endpoint

### PR DESCRIPTION
**Pull request by arielsvn**
## Issue Number

https://github.com/AlexsLemonade/refinebio-frontend/issues/362
https://github.com/AlexsLemonade/refinebio-frontend/issues/371

## Purpose/Implementation Notes

Moves the formatting of platform names into `/platforms`, and changes the names of the fields returned there (ref https://github.com/AlexsLemonade/refinebio-frontend/issues/371#issuecomment-431392398)

Also removes fields `pretty_platforms`, that were returning formatted platform names, since users can get this from `/platforms`.

The filters from the search endpoint were updated to return platform accession codes (instead of platform names), and I used `platform` as the name for the filter parameter. So the API url will look like `/search/?search=human&platform=hgu133plus2`.

## Types of changes

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

I tested this with a local copy of the front-end.

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots

image

### CODE REVIEW

**Comment by arielsvn** [comment]
Removed custom formatting of RNA-Seq platform names, since that will be included with https://github.com/AlexsLemonade/refinebio/pull/783. @kurtwheeler

**Comment by kurtwheeler** [comment]
Cool, new changes also LGTM

**Comment by arielsvn** [comment]
@kurtwheeler I resolved conflicts and removed the fields `pretty_platforms` from search results and experiments details.

**Comment by arielsvn** [comment]
@Miserlou do you think this can be improved in some way? It would be nice to get it merged, with this we'll be able to merge https://github.com/AlexsLemonade/refinebio-frontend/pull/390 as well.

This changes how we format the names of the platforms, by removing `pretty_platforms` from the api responses and sending platform accession codes instead.

I think @kurtwheeler also wanted to get https://github.com/AlexsLemonade/refinebio/pull/783 merged before this one.

**Comment by arielsvn** [comment]
Platform filters were incorporated in the Elastic Search PR https://github.com/AlexsLemonade/refinebio/pull/974. 

Moving the formatting of platform names to the `/platform` endpoint and removing `pretty_platforms` from the serializers might still be relevant.

**Comment by arielsvn** [comment]
Outdated https://github.com/AlexsLemonade/refinebio/issues/1004#issuecomment-459523709

**Pull request closed without merging**
