### PR TITLE
Add blurb for Nomad and Terraform about getting them on the PATH.

### PR DESCRIPTION
**Pull request by kurtwheeler**
## Issue Number

#699 

## Purpose/Implementation Notes

Getting Nomad and Terraform on her PATH were the only things that gave Candace any trouble... so far. She was actually familiar with using her PATH, she just ran into trouble because `sudo` didn't work for her. I'm not experienced with Macs, so I'm not entirely sure how to fix that, and we already link to https://www.nomadproject.io/guides/operations/install/index.html#precompiled-binaries in the readme,  but I do know that moving the binary into `/usr/local/bin` worked for her and is probably the best thing to recommend generally so I've mentioned it in the README.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Functional tests

N/A

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Miserlou** [comment]
I don't think this is the right way to install Nomad on OSX, mine is handled by `homebrew` which makes a symlink from `/usr/local/bin/nomad` to the one in Cellar.

**Comment by cgreene** [comment]
It does look like we have `brew` later, so perhaps the instructions should note that users should only use the brew installation method.

**Comment by kurtwheeler** [comment]
@Miserlou did you look at this link: https://www.nomadproject.io/guides/operations/install/index.html#precompiled-binaries?

It only recommends two ways to do it and that's not one of them. Is that better? I don't know what the difference is and I don't know what Cellar is.

**Comment by kurtwheeler** [comment]
Ohhh Cellar, like a beer cellar? Gotta be a homebrew concept :P

**Comment by kurtwheeler** [comment]
It might make sense to have a Rich write the documentation for Macs since he actually uses one... I know brew is the popular way to install things in Macland, but is it even better than the officially supported methods?

**Comment by Miserlou** [comment]
It's literally just `brew install nomad`

**Comment by kurtwheeler** [comment]
You addressed none of my other comments, such as the fact that the source for these files does not recommend that method. I can put that, but I have literally no context for why that is or isn't a good idea other than you saying that's how you've done it. I am generally uncomfortable writing documentation that I cannot explain the rationale for.

**Comment by Miserlou** [comment]
Then I don't know why this PR was opened at all, since that's exactly what you're doing.

**Pull request closed without merging**
